PRAGMA foreign_keys = ON;
CREATE TABLE CLUB (
 ClubID TEXT PRIMARY KEY NOT NULL,
 ClubName TEXT NOT NULL,
 Capacity INTEGER NOT NULL CHECK(Capacity > 0),
 Fee NUMERIC NOT NULL CHECK(Fee >= 0)
);
CREATE TABLE STUDENT (
 StudentID TEXT PRIMARY KEY NOT NULL,
 StudentName TEXT NOT NULL,
 TutorGroup TEXT NOT NULL,
 ClubID TEXT NOT NULL REFERENCES CLUB(ClubID)
);
INSERT INTO CLUB VALUES ('C01','Coding',20,5.00),('C02','Art',15,8.00),('C03','Music',12,6.50);
INSERT INTO STUDENT VALUES ('S01','Aisha','9A','C01'),('S02','Ben','9B','C02'),('S03','Chen','9A','C01'),('S04','Dina','9C','C03');
